services:
  company-wiki:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./content:/app/content