AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Role for GitHub Actions to deploy to AWS App Runner'

Parameters:
  GitHubOrg:
    Type: String
    Default: 'your-github-org'
    Description: GitHub organization name

  RepositoryName:
    Type: String
    Default: 'company-wiki'
    Description: GitHub repository name

  OIDCProviderArn:
    Type: String
    Description: ARN of the GitHub OIDC provider
    Default: ''

Conditions:
  CreateOIDCProvider: !Equals [!Ref OIDCProviderArn, '']

Resources:
  # Create the OIDC Provider for GitHub if it doesn't exist
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Condition: CreateOIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1

  # IAM Role for GitHub Actions
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${RepositoryName}-github-actions-role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Federated: !If
                - CreateOIDCProvider
                - !GetAtt GitHubOIDCProvider.Arn
                - !Ref OIDCProviderArn
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${RepositoryName}:*
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonECR-FullAccess
      Policies:
        - PolicyName: AppRunnerDeploymentPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # App Runner permissions
              - Effect: Allow
                Action:
                  - apprunner:CreateService
                  - apprunner:UpdateService
                  - apprunner:DeleteService
                  - apprunner:StartDeployment
                  - apprunner:ListServices
                  - apprunner:DescribeService
                  - apprunner:TagResource
                Resource: '*'
              # IAM permissions needed for App Runner
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: '*'
                Condition:
                  StringEquals:
                    'iam:PassedToService': apprunner.amazonaws.com

Outputs:
  RoleARN:
    Description: ARN of the IAM role for GitHub Actions
    Value: !GetAtt GitHubActionsRole.Arn
    Export:
      Name: !Sub ${RepositoryName}-github-actions-role-arn
  
  OIDCProviderArn:
    Description: ARN of the GitHub OIDC provider
    Value: !If
      - CreateOIDCProvider
      - !GetAtt GitHubOIDCProvider.Arn
      - !Ref OIDCProviderArn
    Export:
      Name: GitHubOIDCProviderArn
