AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Role for GitLab CI/CD Deployments'

Parameters:
  GitLabAccountId:
    Type: String
    Description: GitLab AWS account ID used for STS role assumption
    Default: "123456789012"

Resources:
  GitLabDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitLabCICDRole-CompanyWiki
      Description: Role for GitLab CI/CD to deploy the Company Wiki application
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${GitLabAccountId}:root"
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                "sts:ExternalId": "{{ GITLAB_EXTERNAL_ID }}"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonECR-FullAccess
        - arn:aws:iam::aws:policy/AmazonECS-FullAccess
      Policies:
        - PolicyName: DeploymentPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStackResource
                  - cloudformation:DescribeStackResources
                  - cloudformation:GetTemplate
                  - cloudformation:ListStackResources
                  - cloudformation:UpdateStack
                Resource: !Sub "arn:aws:cloudformation:*:${AWS::AccountId}:stack/company-wiki*/*"
              - Effect: Allow
                Action:
                  - ecs:DescribeServices
                  - ecs:DescribeTasks
                  - ecs:ListTasks
                  - ecs:UpdateService
                Resource: "*"
                Condition:
                  StringLike:
                    "ecs:cluster": "*company-wiki*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: !Sub "arn:aws:logs:*:${AWS::AccountId}:log-group:/ecs/company-wiki*"
              - Effect: Allow
                Action:
                  - elasticloadbalancing:DescribeLoadBalancers
                  - elasticloadbalancing:DescribeTargetGroups
                  - elasticloadbalancing:DescribeTargetHealth
                Resource: "*"

Outputs:
  RoleARN:
    Description: ARN of the created IAM Role
    Value: !GetAtt GitLabDeployRole.Arn