version: "3"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: ${DB_PASS:?Database password not set}
      POSTGRES_USER: wikijs
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wikijs"]
      interval: 10s
      timeout: 5s
      retries: 5

  wiki:
    image: requarks/wiki:2
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: ${DB_PASS}
      DB_NAME: wiki
      TZ: ${TZ:-UTC}
    restart: unless-stopped
    ports:
      - "3200:3000"
    volumes:
      - wiki-data:/wiki/data
      - wiki-uploads:/wiki/uploads

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  api-layer:
    build:
      context: ../api-layer
    restart: unless-stopped
    depends_on:
      - wiki
      - redis
    environment:
      WIKI_API_URL: http://wiki:3000/graphql
      WIKI_API_KEY: ${WIKI_API_KEY:-dev_api_key}
      WIKI_ADMIN_USER: ${WIKI_ADMIN_USER:-admin@example.com}
      WIKI_ADMIN_PASSWORD: ${WIKI_ADMIN_PASSWORD:-wikijsrocks}
      JWT_SECRET: ${JWT_SECRET:-dev_jwt_secret}
      REDIS_HOST: redis
      PORT: 3100
      NODE_ENV: ${NODE_ENV:-development}
    ports:
      - "3100:3100"
    volumes:
      - ../api-layer:/app
      - /app/node_modules

  # HIPAA extensions service
  hipaa-extensions:
    build:
      context: ../hipaa-extensions
    restart: unless-stopped
    depends_on:
      - api-layer
      - db
    environment:
      API_LAYER_URL: http://api-layer:3100
      DB_HOST: db
      DB_USER: wikijs
      DB_PASS: ${DB_PASS}
      DB_NAME: wiki
      PORT: 3300
      API_KEY: ${API_KEY:-dev_api_key}
      JWT_SECRET: ${JWT_SECRET:-dev_jwt_secret}
      NODE_ENV: ${NODE_ENV:-development}
      BYPASS_AUTH: ${BYPASS_AUTH:-true}
    ports:
      - "3300:3300"
    volumes:
      - ../hipaa-extensions:/app
      - /app/node_modules

# LLM pipeline service - Commented out for now
#  llm-pipeline:
#    build:
#      context: ../llm-pipeline
#    restart: unless-stopped
#    depends_on:
#      - api-layer
#    environment:
#      API_LAYER_URL: http://api-layer:3100
#      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
#      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
#      DEFAULT_AI_PROVIDER: ${DEFAULT_AI_PROVIDER:-openai}
#      JWT_SECRET: ${JWT_SECRET:-dev_jwt_secret}
#      NODE_ENV: ${NODE_ENV:-development}
#      PORT: 3400
#    ports:
#      - "3400:3400"
#    volumes:
#      - ../llm-pipeline:/app
#      - /app/node_modules
#      - llm-content-cache:/app/content-cache

volumes:
  db-data:
  wiki-data:
  wiki-uploads:
  redis-data: